/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Banco.Banco;
import java.util.ArrayList;
import java.util.Date;
import pojo.Associados;
import pojo.Caixa;
import pojo.PJuridica;
import pojo.Transacao;

/**
 *
 * @author frank
 */
public class TelaCaixa extends javax.swing.JFrame {
    private ArrayList<Associados> FicharioAssociado = new ArrayList<>();
    private ArrayList<PJuridica> FicharioPJuridica = new ArrayList<>();
    private ArrayList<TelaCarne> FicharioCarne = new ArrayList<>();
    private ArrayList<Caixa> FicharioCaixa = new ArrayList<>();
    private ArrayList<Transacao> transacoes = new ArrayList<>();
    private Caixa caixa = new Caixa();
    private Date data_hj = new Date();
    
    private Banco banco = new Banco();

    /**
     * Creates new form TelaCaixa
     */
    public TelaCaixa() {
        FicharioAssociado = (ArrayList<Associados>) banco.Carregar("associados.db");
        FicharioPJuridica = (ArrayList<PJuridica>) banco.Carregar("pjuridica.db");
        FicharioCarne = (ArrayList<TelaCarne>) banco.Carregar("carne.db");
        FicharioCaixa = (ArrayList<Caixa>) banco.Carregar("caixa.db");

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Data = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Pagamentos = new javax.swing.JButton();
        FecharCaixa = new javax.swing.JButton();
        Recebimentos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Data.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        Data.setText("Caixa");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Documento", "Pessoa", "Valor"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Pagamentos.setText("Novo Pagamento");
        Pagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagamentosActionPerformed(evt);
            }
        });

        FecharCaixa.setText("Fechar Caixa");
        FecharCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharCaixaActionPerformed(evt);
            }
        });

        Recebimentos.setText("Novo Recebimento");
        Recebimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecebimentosActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(Data))
                    .add(layout.createSequentialGroup()
                        .add(132, 132, 132)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(layout.createSequentialGroup()
                                .add(Pagamentos)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(Recebimentos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 164, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(260, 260, 260)
                        .add(FecharCaixa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 194, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(Data)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Pagamentos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Recebimentos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 222, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 65, Short.MAX_VALUE)
                .add(FecharCaixa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Data.setText("Caixa "+data_hj);
    }//GEN-LAST:event_formWindowOpened

    private void PagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagamentosActionPerformed
        // TODO add your handling code here:
        TelaPagamentos tela = new TelaPagamentos(new javax.swing.JFrame(), true, FicharioPJuridica);
        tela.setVisible(true);
        transacoes.add(tela.retorna());
        tela=null;
    }//GEN-LAST:event_PagamentosActionPerformed

    private void RecebimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecebimentosActionPerformed
        // TODO add your handling code here:
        TelaRecebimentos tela = new TelaRecebimentos(this, true, FicharioAssociado, FicharioPJuridica, FicharioCarne);
        tela.setVisible(true);
        transacoes.add(tela.retorna());
        tela=null;
    }//GEN-LAST:event_RecebimentosActionPerformed

    private void FecharCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharCaixaActionPerformed
        // TODO add your handling code here:
        caixa.setData(data_hj);
        caixa.setTransacoes(transacoes);
        FicharioCaixa.add(caixa);
        this.dispose();       
    }//GEN-LAST:event_FecharCaixaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCaixa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Data;
    private javax.swing.JButton FecharCaixa;
    private javax.swing.JButton Pagamentos;
    private javax.swing.JButton Recebimentos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
