/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Usuario
 */
public class TelaSistema extends javax.swing.JFrame {

     /**
     * Creates new form TelaPrincipal
     */
    public TelaSistema() {
        initComponents();       

       this.setExtendedState(MAXIMIZED_BOTH);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painelprincipal = new javax.swing.JPanel();
        cadastro = new javax.swing.JButton();
        Movimentacao = new javax.swing.JButton();
        relatorios = new javax.swing.JButton();
        painelcadastro = new javax.swing.JPanel();
        CadastroPJuridica = new javax.swing.JButton();
        CadastroAssociado = new javax.swing.JButton();
        painelrelatorio = new javax.swing.JPanel();
        relatoriocaixa = new javax.swing.JButton();
        relatorioclientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(254, 254, 254));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Logo.setBackground(new java.awt.Color(254, 254, 254));
        Logo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.jpg"))); // NOI18N

        painelprincipal.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        cadastro.setText("cadastros");
        cadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastroMouseClicked(evt);
            }
        });
        cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroActionPerformed(evt);
            }
        });

        Movimentacao.setText("Movimentação");
        Movimentacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MovimentacaoMouseClicked(evt);
            }
        });
        Movimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovimentacaoActionPerformed(evt);
            }
        });

        relatorios.setText("relatorios");
        relatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                relatoriosMouseClicked(evt);
            }
        });
        relatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatoriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelprincipalLayout = new javax.swing.GroupLayout(painelprincipal);
        painelprincipal.setLayout(painelprincipalLayout);
        painelprincipalLayout.setHorizontalGroup(
            painelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Movimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(relatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        painelprincipalLayout.setVerticalGroup(
            painelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelprincipalLayout.createSequentialGroup()
                .addComponent(cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(Movimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(relatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelcadastro.setBorder(new javax.swing.border.MatteBorder(null));

        CadastroPJuridica.setText("Cadastro Pessoa Juridica");
        CadastroPJuridica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastroPJuridicaMouseClicked(evt);
            }
        });

        CadastroAssociado.setText("Cadastro Associado");
        CadastroAssociado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastroAssociadoMouseClicked(evt);
            }
        });
        CadastroAssociado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroAssociadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelcadastroLayout = new javax.swing.GroupLayout(painelcadastro);
        painelcadastro.setLayout(painelcadastroLayout);
        painelcadastroLayout.setHorizontalGroup(
            painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CadastroPJuridica, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
            .addGroup(painelcadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CadastroAssociado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelcadastroLayout.setVerticalGroup(
            painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelcadastroLayout.createSequentialGroup()
                .addComponent(CadastroAssociado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(CadastroPJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelrelatorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelrelatorio.setLayout(new java.awt.GridLayout());

        relatoriocaixa.setText(" Relatorio Caixa");
        relatoriocaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatoriocaixaActionPerformed(evt);
            }
        });
        painelrelatorio.add(relatoriocaixa);

        relatorioclientes.setText("relatorio clientes");
        relatorioclientes.setAlignmentX(0.6F);
        relatorioclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioclientesActionPerformed(evt);
            }
        });
        painelrelatorio.add(relatorioclientes);

        javax.swing.GroupLayout LogoLayout = new javax.swing.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogoLayout.createSequentialGroup()
                        .addComponent(painelprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelcadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painelrelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(273, 273, 273)
                .addComponent(jLabel1)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        LogoLayout.setVerticalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addGroup(LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelcadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painelprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelrelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                    .addComponent(jLabel1))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastroAssociadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastroAssociadoMouseClicked
        // TODO add your handling code here:
        new TelaCadastroAssociados().setVisible(true);
        
    }//GEN-LAST:event_CadastroAssociadoMouseClicked

    private void CadastroPJuridicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastroPJuridicaMouseClicked
        // TODO add your handling code here:
        new TelaCadastroJuridica().setVisible(true);   
    }//GEN-LAST:event_CadastroPJuridicaMouseClicked

    private void MovimentacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovimentacaoMouseClicked
        // TODO add your handling code here:
        new TelaCaixa().setVisible(true);
    }//GEN-LAST:event_MovimentacaoMouseClicked

    private void relatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatoriosActionPerformed
        // TODO add your handling code here:
        if (painelcadastro.isVisible()){
            painelcadastro.setVisible(false);
        }
    }//GEN-LAST:event_relatoriosActionPerformed

    private void cadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroMouseClicked
        // TODO add your handling code here:
         painelcadastro.setVisible(true);
         if (painelrelatorio.isVisible()){
            painelrelatorio.setVisible(false);
        }
    }//GEN-LAST:event_cadastroMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        painelcadastro.setVisible(false);
        painelrelatorio.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void relatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_relatoriosMouseClicked
        // TODO add your handling code here:
        painelrelatorio.setVisible(true);
    }//GEN-LAST:event_relatoriosMouseClicked

    private void relatoriocaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatoriocaixaActionPerformed

        TelaRelatorioCaixa tela = new TelaRelatorioCaixa();
        tela.setVisible(true);
        tela = null;
        
    }//GEN-LAST:event_relatoriocaixaActionPerformed

    private void relatorioclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioclientesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_relatorioclientesActionPerformed

    private void MovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovimentacaoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_MovimentacaoActionPerformed

    private void CadastroAssociadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroAssociadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastroAssociadoActionPerformed

    private void cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastroAssociado;
    private javax.swing.JButton CadastroPJuridica;
    private javax.swing.JPanel Logo;
    private javax.swing.JButton Movimentacao;
    private javax.swing.JButton cadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel painelcadastro;
    private javax.swing.JPanel painelprincipal;
    private javax.swing.JPanel painelrelatorio;
    private javax.swing.JButton relatoriocaixa;
    private javax.swing.JButton relatorioclientes;
    private javax.swing.JButton relatorios;
    // End of variables declaration//GEN-END:variables
}
